### ISSUE TITLE
libcint linking issue

### ISSUE THREAD

**Issue by tmhuysen** [GQCG/gqcp#274]
When compiling an arbitrary test FCI_test.cpp. 
>dyld: Library not loaded: @rpath/libcint.3.dylib
  Referenced from: /Users/quantum/CLionProjects/forks/gqcp/build10/tests/./FCI_test
  Reason: image not found
Abort trap: 6

lib folder contains:
libcint.3.0.14.dylib
libcint.3.dylib
libcint.dylib

**Comment by guacke** [comment]
This issue can be resolved by installing libcint through conda (conda install -c pyscf libcint), pointing CLion to the Conda environment:

Clion > Preferences > Build, Execution, Deployment > Python Interpreter

and passing the required options to CMake. E.g.:

Clion > Preferences > Build, Execution, Deployment > CMake > CMake options: -DLIBCINTROOT=/anaconda3/envs/gqcg -DLIBINTROOT=/anaconda3/envs/gqcg -DMKLROOT=/anaconda3/envs/gqcg

**Comment by guacke** [comment]
As mentioned by tmhuysen, another option is to use the static library (see Libcint documentation for more information). This seems to be the preferred option on MacOS systems, as the solution reported above seems to only work on Linux systems. My guess is that there is a bug in the build scripts of Libcint. If I figure out what that bug is, I will PR a fix to Libcint.
