### ISSUE TITLE
Cmake Int2 error

### ISSUE THREAD

**Issue by tmhuysen** [GQCG/gqcp#281]
Currently when I use Cmake I get the following error:

>CMake Error at /opt/local/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Int2 (missing: Int2_INCLUDE_DIR Int2_LIBRARY)

I have tried `export Int2_ROOT_DIR=/usr/local/libint/2.3.1` in my profile but to no avail.

**Comment by tmhuysen** [comment]
Adding the export and changing the lines in `FindInt2.cmake` to `$ENV`:
>find_path(Int2_INCLUDE_DIR libint2.hpp HINTS $ENV{Int2_ROOT_DIR}/include)
>find_library(Int2_LIBRARY Int2 HINTS $ENV{Int2_ROOT_DIR}/lib)

But that's not how I'm suppose to fix it.

**Comment by guacke** [comment]
Have you tried setting the -DCMAKE_INCLUDE_PATH=... and --DCMAKE_LIBRARY_PATH=... settings documented in the `CMake options` section of the README?

**Comment by guacke** [comment]
The above comment resolved the issue.

**Comment by lelemmen** [comment]
> Have you tried setting the `-DCMAKE_INCLUDE_PATH=..`. and `-DCMAKE_LIBRARY_PATH=...` settings documented in the `CMake options` section of the README?

Note that it is **very important** that **BOTH options** are specified. If a standard installation of libint2 (v2.3.1) is used,

```cmake
cmake .. -DCMAKE_INCLUDE_PATH="/usr/local/libint/2.3.1/include"
```

is not enough and will still result in the above-mentioned error. The correct command is

```cmake
cmake .. -DCMAKE_INCLUDE_PATH="/usr/local/libint/2.3.1/include" -DCMAKE_LIBRARY_PATH="/usr/local/libint/2.3.1/lib"
```

Due to the nature of the current `FindInt2.cmake`-file, the following command also ought to work (at the moment):

```cmake
cmake .. -Int2_ROOT_DIR="/usr/local/libint/2.3.1"
```

but I would prefer the first alternative.
