### ISSUE TITLE
Printing gqcpy Tensors

### ISSUE THREAD

**Issue by dariatols** [GQCG/GQCP#591]
It is unclear to me how I can see the values of the T2-amplitudes within a `CCSDEnvironment`. When I try to print the T2-amplitudes as a `Tensor`, this gives an error. Is this due to the fact that I should write the bindings for `GQCP::Tensor`?

<img width="1227" alt="Screenshot 2020-06-23 at 00 23 29" src="https://user-images.githubusercontent.com/33431368/85341336-30a8c280-b4e8-11ea-995a-20d4705c7114.png">

**Comment by lelemmen** [comment]
You are correct that `T2Amplitudes` exposes the values of the T2-amplitudes in their tensor-like form `T2(i,a,j,b)`. 

The reason why we haven't written any `GQCP::Tensor` bindings is because pybind11 has already written `Eigen::Tensor` bindings. Since `GQCP::Tensor` derives from `Eigen::Tensor`, all we need to do in the python bindings is:
- `#include <pybind11/Eigen.h>`
- write a binding for `asTensor()`, in which the bound lambda function converts the `GQCP::Tensor` into an `Eigen::Tensor`. This can easily be done through the `.Eigen()` API that is available for `GQCP::Tensor`s, which does that conversion for us.

You can find example of a similar situation in `SQTwoElectronOperator_bindings.cpp` for the `parameters()` API.

**Comment by lelemmen** [comment]
@dariatols Was this issue resolved with the previous answer? If so, please "thumbs it up" and I will close the issue.

**Comment by dariatols** [comment]
@lelemmen Thank you for your help, I still have to implement these bindings but if you want, you can close this issue.
