### ISSUE TITLE
K or M for the number of spinors?

### ISSUE THREAD

**Issue by dariatols** [GQCG/GQCP#658]
It seems like there is a minor consistency "error" in the `SpinUnresolvedONVBasis.hpp`. Helgaker uses $n$ for the number of orbitals. I recall that we used $K$ for the number of spinors throughout the `CCD` code.
![Screenshot 2020-09-02 at 13 20 43](https://user-images.githubusercontent.com/33431368/91975156-4247eb00-ed1f-11ea-863d-ef30eae3c753.png)

**Comment by lelemmen** [comment]
You're complete correct. All the code in `ONVBasis/`, `Processing/DensityMatrices` and `QCMethod/CI/HamiltonianBuilders` is pretty old, and hasn't been scrutinized for these naming errors.

For clarity, `M` should refer to the number of spinors, `K` to the number of basis functions. The reason why Helgaker in his discussion on the addressing scheme uses `n` for the number of orbitals is still unclear to me.

For further reference, please feel free to tag me in issues and PRs, but leave the actual assignment to myself. Instead of uploading a screenshot, it's also possible to [link to a couple of source code lines](https://docs.github.com/en/github/managing-your-work-on-github/creating-a-permanent-link-to-a-code-snippet).
