### ISSUE TITLE
Warnings generated where member functions are not marked as 'override'.

### ISSUE THREAD

**Issue by dariatols** [GQCG/GQCP#750]
**Describe the bug**
Compiling GQCP (develop branch) generates a whole lot of warnings `/Users/dariatolstykh/work/gqcg/GQCP/gqcp/include/Basis/SpinorBasis/SimpleSpinorBasis.hpp:162:22: warning: 'transformed' overrides a member function but is not marked 'override'` during compilation. 

**To Reproduce**
Compiling develop without warnings.

**Expected behavior**
Compilation without warnings.

**Screenshots and logs**
![Screenshot 2020-10-30 at 09 25 48](https://user-images.githubusercontent.com/33431368/97677048-ef29b480-1a91-11eb-934c-39016e846e51.png)

**Operating system**
 - OS: macOS
 - Version 10.15.7

**Comment by xdvriend** [comment]
I still get some warnings due to something being wrong with the vector space arithmetic in the USQTwoElectronOperator:

![Screenshot 2020-10-30 at 13 43 55](https://user-images.githubusercontent.com/54795591/97706508-1e521d00-1ab6-11eb-86e9-f27b77bd75a5.png)
![Screenshot 2020-10-30 at 13 44 20](https://user-images.githubusercontent.com/54795591/97706515-20b47700-1ab6-11eb-9863-66bebd01eae4.png)
