### ISSUE TITLE
Conda pipeline for macOS

### ISSUE THREAD

**Issue by lelemmen** [GQCG/GQCP#814]

**Comment by guacke** [comment]
This issue is blocked by the Conda installer for Libint (https://github.com/GQCG-oss/libint/pull/4). More precisely, Libint has switched recently to CMake instead of autotools because of the problems associated with the latter. As we are currently still using 2.4.2 (autotools based), we first need to upgrade to the latest version of Libint before I can resolve this issue.

**Comment by guacke** [comment]
See #547.
